// ════════════════════════════════════════════════════════════════════════════
// scripts/build.js — bundle JS + CSS for Cloudflare Pages
//
// Two outputs:
//   docs/js/bundle.js   — minified ESM, entry docs/js/app.js, all imports
//   docs/css/bundle.css — concatenated @layer cascade in token order
//
// Both files are gitignored (build artifacts). index.html loads them directly.
// Run via `npm run build` (one-shot) or `npm run build:watch`.
// ════════════════════════════════════════════════════════════════════════════

import { build } from 'esbuild';
import { writeFile, mkdir, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const DOCS = join(ROOT, 'docs');
const WATCH = process.argv.includes('--watch');

const JS_BUNDLE = join(DOCS, 'js', 'bundle.js');
const CSS_BUNDLE = join(DOCS, 'css', 'bundle.css');

// Synthetic CSS entry: declares the layer order up front, then @imports each
// file. esbuild inlines @imports into the bundle (when inlined imports is on),
// but @layer rules must come BEFORE any rules they govern. The layer-list at
// the top of this file is the canonical source of truth — same order as
// tokens.css line 13 (`@layer tokens, base, layout, components, app;`).
const CSS_ENTRY = join(HERE, '.css-entry.css');
const CSS_ENTRY_SRC = `/* Generated by scripts/build.js — do not edit. */
@layer tokens, base, layout, components, app;
@import "../docs/css/tokens.css" layer(tokens);
@import "../docs/css/base.css" layer(base);
@import "../docs/css/layout.css" layer(layout);
@import "../docs/css/components.css" layer(components);
@import "../docs/css/app.css" layer(app);
`;

async function ensureDirs() {
  await mkdir(dirname(JS_BUNDLE), { recursive: true });
  await mkdir(dirname(CSS_BUNDLE), { recursive: true });
  await writeFile(CSS_ENTRY, CSS_ENTRY_SRC);
}

async function buildJS() {
  await build({
    entryPoints: [join(HERE, 'app.entry.js')],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    minify: true,
    sourcemap: false,
    outfile: JS_BUNDLE,
    logLevel: 'info',
  });
}

async function buildCSS() {
  await build({
    entryPoints: [CSS_ENTRY],
    bundle: true,
    loader: { '.css': 'css' },
    outfile: CSS_BUNDLE,
    logLevel: 'info',
  });
}

async function buildAll() {
  await ensureDirs();
  await Promise.all([buildJS(), buildCSS()]);
  console.log(`✓ built ${JS_BUNDLE.replace(ROOT + '/', '')}`);
  console.log(`✓ built ${CSS_BUNDLE.replace(ROOT + '/', '')}`);
}

async function watch() {
  await ensureDirs();
  const ctxJS = await build({
    entryPoints: [join(HERE, 'app.entry.js')],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    minify: true,
    sourcemap: false,
    outfile: JS_BUNDLE,
    logLevel: 'info',
  });
  const ctxCSS = await build({
    entryPoints: [CSS_ENTRY],
    bundle: true,
    loader: { '.css': 'css' },
    outfile: CSS_BUNDLE,
    logLevel: 'info',
  });
  await ctxJS.watch();
  await ctxCSS.watch();
  console.log('watching for changes… (Ctrl+C to stop)');
}

if (WATCH) {
  await watch();
} else {
  await buildAll();
}
